INPUT_CMDS_LUT = 'cat'
SHOW_LIVE_CMD_LUT = 'pip'
EXIT_PYSHELL_CMD = 'exit'
PYTHON_VAR_DELIMETER = '@'
PYTHON_SINGLE_LINE_INPUT_DELEMETER = '>>>'
PYTHON_MULTI_LINE_INPUT_DELIMETER = '...'
COMPLEX_SYMBOLS = ['||', ';', '&&']
DISPLAY = ('vim', 'cat', 'vi', 'less')